name: Run Node Script Message

on:
  workflow_dispatch:
    inputs:
      message:
        required: true

jobs:
  test:
    name: "Run on node-${{ matrix.node_version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18, 20, 22]
        include:
          - os: macos-latest
            node_version: 20
          - os: windows-latest
            node_version: 20
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: "https://registry.npmjs.org"

      - name: Run script
        run: node --eval "${{ github.event.inputs.message }}"
